import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Steps_Daily {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final String row_id;

  final String patient_id; 
  final String day;
  final String time;
  final int value;

  //Default constructor
  Steps_Daily(this.row_id, this.patient_id, this.day, this.time, this.value);
  
}//Todo